development:
  adapter: postgresql
  encoding: unicode
  database: cast2dev_database_dev
  pool: 5
  username: vagrant
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: cast2dev_database_test
  pool: 5
  username: vagrant
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: cast2dev_database_pro
  pool: 5
  password:
